# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27b6817bdba411e8714b1634df73a4308a402ba1458d8b51ca3f3ea2e35c82a97362d597cdac2624278c7aa3d5cbdd2defc750b9ba00caba218e25b3cfdd65d2

test:
  secret_key_base: 6bab2721ef5d720caa135a7c00e7f87eeb635dad3fd8c64c0e28c2a7df47eeee22bea22c01c52636bf839a139dfb30ab5a4bf0fef8cbfa5abcc4a1f19494f96a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
